swagger: '1.0'
info:
  description: >-
    Web service that returns numbers of tribonacci sequence
  version: 0.0.1
  title: tribonacci web
basePath: /v1
schemes:
  - http
paths:
  /tribonacci:
    get:
      description: Returns member of tribonacci sequence
      produces:
        - application/json
      parameters:
        - name: number
          in: query
          description: Number of tribonacci sequence member to return
          required: true
          type: integer
          minimum: 1
      responses:
        '200':
          description: successful operation
          schema:
            type: number
        '400':
          description: Invalid request
